mackerelio/mkr

- commands.go
ref https://github.com/mackerelio/mackerel-client-go/pull/2
> Follow mackerel client go

- .travis.yml
- Makefile
- commands.go
- monitors.go
- monitors_test.go
implementing `monitors` subcommand
> implement manipulating monitoring rules

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- Create deb/rpm package for Linux release #11
> Release version 0.4.1

- script/releng
* show diff and pull-request body before push
* abort script when GitHub API returns non success response.
> [nit] Improve releng to avoid a mistakes

- README.md
> [nit] Use https for README badges.

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- append newline to the end of monitors.json #23
- fix printMonitor #24
- fix diff output between slices #25
> Release version 0.7.0

- alerts.go
- commands.go
- monitors.go
Mostly simple fixes of English that felt wrong to me.
> Fixed the english used in the command descriptions

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- fix handling host-status option #37
> Release version 0.8.1

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- Support displayName of host's json #39
> Release version 0.9.0

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- use GOARCH=amd64 for now #41
> Release version 0.9.1

- .travis.yml
- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- script/releng
- Refactoring release process #48
- support `isMute` field of monitors #49
- fix tests with isMute #50
- support boolean at isEmpty #51
- bump up go version to 1.6.2 #52
> Release version 0.10.0

- alerts.go
- commands.go
- monitors.go
interface change. 
ref: https://github.com/codegangsta/cli/pull/361
> fix signnatures. codegangsta/cli

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- fix signnatures. codegangsta/cli #54
> Release version 0.10.1

- commands.go
This pr depends on https://github.com/mackerelio/mackerel-client-go/pull/26.
It uses https://mackerel.io/api-docs/entry/hosts#update-roles internally instead of https://mackerel.io/api-docs/entry/hosts#update-information.
~~It doesn't support empty roles as arguments due to the limitation of cli library.~~
I didn't add test yet because I cannot find existing tests for `doUpdate`, but I guess we should add test commands.go, especially for `doUpdate` because of the complexity of `doUpdate`.
I'll try to write tests later.
> Add flag to overwrite host's roles 

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- add dashboard generator #56
- Add flag to overwrite host's roles  #58
> Release version 0.11.0

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
> Release version 0.11.1

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- replace angle brackets for json #63
> Release version 0.11.2

- monitors.go
> fix `validateRules()`,  when monitor has rule of "expression".

- monitors_test.go
This pull request fixes test according to mackerel-client-go changes https://github.com/mackerelio/mackerel-client-go/pull/37
> fix test according to mackerel-client-go changes

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- Support expression monitor alerts in mkr alerts list #78
> Release version 0.14.0

- monitors.go
ref: https://github.com/yudai/gojsondiff/commit/7b1b7adf999dab73a6eb02669c3d82dbb27a3dd6
(Maybe we need to introduce some version lock for dependencies like vendoring?)
> formatter.NewAsciiFormatter now needs config

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- formatter.NewAsciiFormatter now needs config #80
> Release version 0.14.1

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- [monitors diff] Add the "to-remote" bool flag #82
> Release version 0.14.2

- CHANGELOG.md
- packaging/deb/debian/changelog
- packaging/rpm/mkr.spec
- Support annotations command for graph annotation #83
- Improve help management and fix usage help for command #85
- remove unused functions #86
> Release version 0.14.3

- dashboards.go
- dashboards_test.go
Enable specifying the graph title in expression graph.
> [dashboards] Add title param to expression graph

- commands.go
conffile -> confFile. Sorry for the minor pr :)
> Stick to a camel case

- script/cpanfile
ref: https://github.com/mackerelio/Mackerel-ReleaseUtils/pull/2
> Update Mackerel::ReleaseUtils to check git workspace is clean

- config.go
- config_test.go
Ref: https://github.com/mackerelio/mackerel-agent/pull/417
> Use new API BaseURL

- commands.go
- config_test.go
Add metrics command for fetching the metric by `/api/v0/hosts/<hostId>/metrics` and `/api/v0/services/<serviceName>/metrics`
> Add metrics command

- commands.go
> fix hostId option flag in the command help of throw and metrics commands

- throw.go
> Fix mkr throw --retry not working

- Dockerfile
- README.md
- change baseimage to alpine:3.7
> fix Dockerfile to create alpine based docker image

- plugin/install.go
It's recently *rewritten*, and its interface changed.
> Follow https://github.com/mholt/archiver's change

- alerts.go
> avoid out of range exception in mkr alerts

- alerts.go
This pull request refactors the duplicated codes in alerts.go.
> [nit] refactor alerts commands

- commands.go
- commands_test.go
- config.go
- dashboards.go
- mkr.go
Fixed a few things that are trivial but better way.
> [nit] refactored several points

- hosts/command.go
Fix a bug introduced in  #189.
> [hosts] fix status argument

- hosts/app.go
- hosts/app_test.go
- hosts/command.go
This pull request adds tests to the app of hosts package.
> Add tests for hosts package

- commands.go
- mackerelclient/client.go
- mackerelclient/mock_client.go
- org/app.go
- org/app_test.go
- org/command.go
- Separate org subcommand implementation to ./org/
- Add tests
> Create org package and add tests for org subcommand

- alerts.go
- annotations.go
- checks/checker.go
- commands.go
- commands_test.go
- dashboards.go
- go.mod
- go.sum
- hosts/commandCreate.go
- hosts/commandHosts.go
- mackerelclient/new.go
- mkr.go
- monitors.go
- org/command.go
- plugin/commands.go
- plugin/install.go
- plugin/install_test.go
- services/command.go
- throw.go
- wrap/command.go
- wrap/wrap.go
- wrap/wrap_test.go
> rename gopkg.in/urfave/cli.v1 -> github.com/urfave/cli

- .dependabot/config.yml
- .gitignore
I added docker package manager and existent configs on Dependabot.
> [Dependabot]add docker package manager

- README.md
Reported at #302.  Currently this section is outdated.
> Update `Installation` section of README 

- .travis.yml
- Makefile
- packaging/deb-v2/debian/control
- packaging/deb/debian/control
- packaging/rpm/mkr-v2.spec
- packaging/rpm/mkr.spec
I added recipes to make the packages for arm64 architecture, and fixed Architecture of deb to be correct.
> add arm64 packages, and fix Architecture field of deb

- Dockerfile
> revert go1.15-alpine

- .github/workflows/ci.yml
refer: https://github.com/mackerelio/mkr/runs/1862118345?check_suite_focus=true#step:5:38
> recover checkout for mackerel-github-release

- .github/workflows/ci.yml
change to one with appropriate privileges
> replace token

- .github/workflows/ci.yml
refer https://github.com/mackerelio/homebrew-mackerel-agent/pull/27
> added repository_dispatch to homebrew-mackerel-agent

- .github/workflows/ci.yml
- Dockerfile
I also dropped matrix tests for multiple Go versions.
> build / test with Go 1.16

- go.sum
refer https://github.com/mackerelio/mkr/runs/2009770748
> fix CI build stage.

- .github/workflows/ci.yml
I made a mistake in specifying the option
> fix option at repository-dispatch

- go.mod
- go.sum
- hosts/app_test.go
refer https://github.com/mackerelio/mackerel-client-go/pull/122
> update mackerel-client-go 0.16.0

- Makefile
Same motivation as https://github.com/mackerelio/mackerel-agent/pull/734.
> Add arm64/darwin build artifacts to GitHub release

- commands.go
- go.mod
- go.sum
- hosts/app.go
- hosts/commandCreate.go
Added features "memo on host" supported in 0.20.0 of github.com/mackerelio/mackerel-client-go
> added memo on host

- .github/workflows/ci.yml
`if` and `needs` parts are commented for confirmation purposes.
In successor PR, they and `login`, `push : true` part will be uncommented.
> Add a job to build docker images and push to DockerHub

- .github/workflows/ci.yml
- Dockerfile
- go.mod
> upgrade Go version: 1.16 -> 1.17

- README.md
- example/metrics.txt
- remove unused example file
- update README
> refine README and others

- .github/workflows/ci.yml
refs. https://github.com/actions/runner-images
> update macos,windows Actions Runner Image.

- .github/workflows/ci.yml
we decided push a container to new registry.
> added container registry ECR Public

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
- tools.go
> use Go 1.24

- plugin/install.go
I got errors when `mkr install` with an upgrade option.
```
Failed to install plugin while extracting and placing: handling file 3: mackerel-plugin-maxcpu: open /opt/mackerel-agent/plugins/bin/mackerel-plugin-maxcpu: text file busy
```
I got this error because maxcpu is running as daemon, but this may occur with plugins that take a long time to execute.
This PR makes create temp file and rename to destination when upgrade plugins.
> Make plugin install safety to avoid text busy error

- CHANGELOG.md
- packaging/deb-v2/debian/changelog
- packaging/rpm/mkr-v2.spec
> Revert "Release version 0.62.1"
