commands.go
So you can customize output of `mkr hosts` without using external programs like `jq`:
~~~
$ mkr hosts -f '{{range .}}{{if (len .Interfaces)}}{{(index .Interfaces 0).IPAddress}}{{end}}{{"\t"}}{{.Name}}{{"\n"}}{{end}}'
127.0.0.1   myhost1
127.0.0.2   myhost2
~~~
=> add -f flag to hosts command to format the output

commands.go, config.go, config_test.go, mkr.go
I want to specify conf file path using command line option.
This patch adds a `--conf` option like bellow,
```
$ mkr --conf=/usr/loca/etc/mackerel-agent.conf hosts
```
thank you for your review.
=> add --conf option to specify conf file path

commands.go
* this patch is a workaround fix.
* Please let us know what you think
* `update` command overrides host meta data using empty data.
* `update`command with `-R` option requires name.
* fetch host data before execute update for autofilling lack data.
=> Fix update command as firstaid

commands.go
Fix update command bug that the 'mkr update' overwrite each host's 'name' as the same 'name' value when '-n' option value is empty and multiple hostIds are passed
=> mkr update command bug about overwriting hostname

monitors.go, monitors_test.go
This pull request suppress to display empty fields.
For example, `"scopes"` field are shown as follows, but this field should not be outputted.
```
Summary: 1 modify, 0 append, 0 remove
{
"name": "blog.stanaka.org",
"type": "external",
"metric": "",
"operator": "",
"warning": 0.000000,
"critical": 0.000000,
"duration": 0,
"url": "http://blog.stanaka.org",
"scopes": [
],
"service": "stanaka",
"maxCheckAttempts": 1.000000,
"excludeScopes": [
],
-  "responseTimeCritical": 10000.000000,
+  "responseTimeCritical": 0.000000,
-  "responseTimeWarning": 5000.000000,
+  "responseTimeWarning": 0.000000,
-  "responseTimeDuration": 3.000000,
+  "responseTimeDuration": 0.000000,
},
```
=> Suppress to display empty fields when mkr monitors diff

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mkr.spec
update https://github.com/mackerelio/mackerel-client-go dependency.
- support `notificationIntervai` field in monitors (stanaka)
- [bug] fix json parameter s/hostID/hostId/g (Songmu)
=> Release version 0.7.1

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mkr.spec
- support alerts subcommand #31
- Fix README example about mkr throw #32
- Build with Go 1.5 #33
- Fixed the english used in the command descriptions #35
=> Release version 0.8.0

alerts.go
```
% mkr alerts list --host-status working
2Aebsaa 2016-01-07 18:37:34 WARNING  memory% 98.02 > 98.00 db01 working [foo:db]
2AcM2nn 2016-01-07 06:43:01 WARNING  memory% 98.12 > 98.00 db02 working [foo:db]
```
=> fix handling host-status option

format.go, monitors.go
```
$mkr monitors
{
"id": "xxxxxxx",
"name": "expression test 2",
"type": "expression",
"operator": "\u003e",
"warning": 0.02,
"critical": 0.01
}
```
`operator` value is encoded on standard out
=> replace angle brackets for json

Makefile
This pull request introduces a check of the output of `gofmt -s`. This will keep the coding style consistent.
=> [nit] Check gofmt -s on Travis

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mkr.spec
- fix `validateRules()`,  when monitor has rule of "expression". #66
=> Release version 0.11.3

alerts.go, commands.go, dashboards.go, mkr.go, monitors.go
github/codegangsta/cli was moved to github.com/urfave/cli.
I use gopkg.in because urfave/cli use version tag.
=> Rename a dependent package

alerts.go, commands.go, config.go, config_test.go, dashboards.go, mkr.go, monitors.go, test/mackerel-agent.conf
Same as mackerel-agent's `-apibase` option.
- if `-apibase` option is supplied, specified value will be used.
- If `-apibase` is not supplied but specified in your mackerel-agent.conf, the value will be used.
- By this behavior,  default apibase is `https://mackerel.io/`. (Keep current behavior)
=> Support `-apibase` option

commands.go
We can throw host metrics via `mkr throw -H <hostId>`, and one might combine this feature with mackerel-agent-plugins to post custom host metrics like this:
```
$ mackerel-plugin-mysql --host myrds.com | mkr throw -H <rdsHostId>
```
But, outputs by mackerel-agent-plugin don't have `custom.` prefix in metric name. (Because the prefix is added by mackerel-agent, not by mackerel-agent-plugin).
So I'd like to change `mkr`'s behavior:
```
$ echo -ne 'some.key' '\t' 12345 '\t' 1476864005 | mkr throw -H <hostId>
```
This command posts following metrics:
```
[{"hostId":"<hostId>","name":"some.key","time":1476864005,"value":12345}]
```
```
$ echo -ne 'some.key' '\t' 12345 '\t' 1476864005 | mkr throw -H <hostId>
```
This command will post following metrics:
``` …
```
=> [breaking change] Prepend `custom.` prefix to host metric name by default

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mkr.spec
- Rename a dependent package #68
- Support `-apibase` option #69
- [breaking change] Prepend `custom.` prefix to host metric name by default #70
=> Release version 0.12.0

alerts.go
alert.type can be "check", but in case of alert.type is "check", monitor is nil anyway.
=> remove unreachable code: monitor type cannot be "check"

monitors.go, monitors_test.go
This p-r introduces https://github.com/yudai/gojsondiff for `mkr monitors diff` and removes the existed ad-hoc monitor diff implementation.
The ad-hoc implementation only supported flat JSON field and array of string, but we'll need to support more complex field like `headers` field for external monitoring. https://mackerel.io/api-docs/entry/monitors#create. We don't want to maintain ad-hoc monitor diff implementation anymore.
The format of output JSON diff is slightly different from old one, but I think the difference is acceptable.
=> Introduce yudai/gojsondiff for `mkr monitors diff`

alerts.go, alerts_test.go, monitors.go, monitors_test.go
This p-r catches up the change of monitor interface of mackerel-client.go https://github.com/mackerelio/mackerel-client-go/issues/30
https://github.com/mackerelio/mackerel-client-go/issues/31 and https://github.com/mackerelio/mackerel-client-go/issues/32 must be merged before merging this p-r.
=> catch up monitor interface changes of mackerel-client-go

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mkr.spec
- remove unreachable code: monitor type cannot be "check" #72
- Fix the links to the api documents #73
- catch up monitor interface changes of mackerel-client-go #74
- Introduce yudai/gojsondiff for `mkr monitors diff` #75
- fix test according to mackerel-client-go changes #76
=> Release version 0.13.0

alerts.go, alerts_test.go
This pull request adds support for expression monitor alerts. It prints the expression in the configuration, current value, operator and threshold.
=> Support expression monitor alerts in mkr alerts list

monitors.go
We are running `mkr monitors diff` to capture the difference by the GUI.
- ref. http://arata.hatenadiary.com/entry/2016/12/11/090000
Current output consists of the difference on the remote server represented by minus and the difference on the local file represented by plus. 
This is useful for the use case that run`mkr monitors push` afterwards. 
However if you run `mkr monitor pull` after `mkr monitor diff`, it is more useful to invert the output and the current one confuses us.
=> [monitors diff] Add the "to-remote" bool flag

commands.go, monitors.go
appendDiff is unused since #75
isEmpty seems to exist for calculating monitor diff, but it's unused too.
I also remove 2 unused debug functions (debug, assert).
```
$ go get honnef.co/go/tools/cmd/unused
$ unused github.com/mackerelio/mkr
/home/haya14busa/src/github.com/mackerelio/mkr/commands.go:155:6: func debug is unused (U1000)
/home/haya14busa/src/github.com/mackerelio/mkr/commands.go:161:6: func assert is unused (U1000)
/home/haya14busa/src/github.com/mackerelio/mkr/monitors.go:175:6: func isEmpty is unused (U1000)
/home/haya14busa/src/github.com/mackerelio/mkr/monitors.go:201:6: func appendDiff is unused (U1000)
```
https://github.com/dominikh/go-tools/tree/master/cmd/unused
=> remove unused functions

alerts.go, commands.go, commands_test.go, dashboards.go, monitors.go
`var commandDocs = map[string]commandDoc{...}` has worked to some
extent, but it didn't work with sub-sub commands.
e.g. $ mkr monitors diff -h shows wrong usage as following.
USAGE:
mkr diff
Old implementation seems to intend to enhance [Usage] document to show
available flags ([command options]).
commit: 064e51f5bd0d992b053e40474e93ddc269fceeb4
This commit use urfave/cli.Command.ArgsUsage field for [Usage] document.
godoc: https://godoc.org/github.com/urfave/cli#Command
=> Improve help management and fix usage help for command

.travis.yml
Since https://github.com/akatu/github-release (release dependency) now requires go >= 1.7, our easiest solution is to bump go.
ref: https://travis-ci.org/mackerelio/mkr/builds/216646176 / https://github.com/aktau/github-release/commit/f2ebbf795aa4ab88b13c940c7df6807ce79c2b08
(`setIndent` is introduced on go 1.7: https://golang.org/doc/go1.7#encoding_json)
=> bump Go to 1.8

commands.go
This PR depends on https://github.com/mackerelio/mackerel-client-go/pull/44 .
```
$ mkr services -h
mkr services - List services
USAGE:
mkr services [arguments...]
DESCRIPTION:
List the information of the services.
Requests "GET /api/v0/services". See https://mackerel.io/api-docs/entry/services#list.
```
=> Add services subcommand

commands.go
With this patch, `mkr create --customIdentifier ${myName} ${hostName}` will be supported.
=> add --customIdentifier option to mkr create

commands.go, config.go, config_test.go, mkr.go, test/mackerel-agent-no-base.conf
I'm not sure this is the best……
- If `-apibase` option is specified, it will be used
- If `-apibase` is not specified but `apibase` is specified in mackerel-agent configuration file, it will be used (NEW!!)
- When neither of them are present, default (mackerel.io) will be used
=> Prefer apibase in mackerel-agent confFile

commands.go
This pull request fixes mkr fetch command to fetch huge number of hosts per one command.
=> Support fetch command to retrieve many hosts

plugin/commands.go, plugin/commands_test.go
This pull request does
- Rename parseInstallTarget to newInstallTargetFromString
- because it is a kind of constructor of installTarget
- Parse install target string more strictly
Before, parseInstallTarget is success unexpectedly if target string is
- `mackerelio/`
- `/sample-plugin`
- `mackerel/io/plugin`
And parseInstallTarget is failed unexpectedly if target string is
- `mackerelio/mackerel-plugin-sample@release/0.0.1`
- `release/0.0.1` can be specified as git tag name
So I fixed it.
The diff is big because I move a method down.  I recommend a reviewer to watch one by one commit.
=> Check install target string more strictly

plugin/commands.go, plugin/commands_test.go, plugin/github.go, plugin/github_test.go, plugin/testdata/gitconfig
This pull request implements 
- installing a mackerel plugin from latest Github Releases
- handling github token
- get github token from `GITHUB_TOKEN` env or `github.token` in .gitconfig
For example, if we execute `mkr plugin install shibayu36/mackerel-plugin-sample`, then 
- mkr will looks for latest release (from https://github.com/shibayu36/mackerel-plugin-sample/releases )
- mkr will find `v0.0.5` release
- then mkr will install this release (like `mkr plugin install shibayu36/mackerel-plugin-sample@v0.0.5`)
Change commands.go like following, and execute in your terminal.
- `go run $(go list -f '{{join .GoFiles " "}}') plugin install --prefix ./mackerel-agent/plugins shibayu36/mackerel-plugin-sample`
- `go run $(go list -f '{{join .GoFiles " "}}') plugin install --prefix …
=> Install a plugin from latest Github Releases

plugin/commands.go, plugin/commands_test.go
This pull request add `--overwrite` flag for `mkr plugin install` to force overwriting an existing plugin.
At first, fix commands.go like https://github.com/mackerelio/mkr/pull/123 .  And then
- `go run $(go list -f '{{join .GoFiles " "}}') plugin install --prefix ./mackerel-agent/plugins --overwrite mackerel-plugin-sample`
=> Add overwrite flag to overwrite an existing plugin

plugin/client.go, plugin/install_target.go, plugin/install_test.go
By this patch, we can do the following things.
```sh
mkr plugin install https://www.example.com/mackerel-plugin-hoge.zip
```
supported URL schemes as follows.
- http
- https
- file
=> [plugin.install] support direct URL target

plugin/install.go
I added following plugin documents link in `mkr plugin install --help`.
- https://mackerel.io/docs/entry/advanced/install-plugin-by-mkr
- https://mackerel.io/docs/entry/advanced/make-plugin-corresponding-to-installer
=> Add plugin document links

README.md
This is a nitpick fix, host id argument is required for mkr fetch.
=> [nit] fix example of mkr fetch in README.md: hostId is required

plugin/install.go, plugin/install_test.go
In the current implementation, `mkr plugin install mackerel-plugin-sample` on Windows installs the plugin archive (~.zip) in the bin directory. We cannot distinguish the plugin executable and archive by file permission on Windows.
=> Fix copying plugin archives while installing a plugin on Windows

alerts.go, alerts_test.go, monitors_test.go
Empty threshold is supported in https://github.com/mackerelio/mackerel-client-go/pull/55 and this is an empty pull request to reflect the changes into CHANGELOG.
Edit: After all I have to fix some code for mkr alerts and the tests.
=> Support empty threshold for monitors

plugin/install.go, plugin/install_target.go
Installing by direct URL is supported by https://github.com/mackerelio/mkr/pull/130.  But it wasn't documented.
This PR adds <direct_url> help.
=> Add <direct_url> help

plugin/install.go, plugin/install_target.go, plugin/install_test.go, plugin/meta_data_store.go, plugin/meta_data_store_test.go
I added `--upgrade` option to `plugin install`.
`--overwrite` option always download archives from remote, and overwrite files.
But I want to reduce installation time and bandwidth if it is not necessary.
This PR add a meta data store for plugins.
Meta data(release_tag) stored at installed will be compared at next time.
Works as below.
metadata is created after Install a plugin.
```console
$ mkr plugin install mackerelio/mackerel-plugin-sample
Downloading https://github.com/mackerelio/mackerel-plugin-sample/releases/download/v0.0.3/mackerel-plugin-sample_darwin_amd64.zip
Installing /opt/mackerel-agent/plugins/bin/mackerel-plugin-sample
Successfully installed mackerelio/mackerel-plugin-sample
$ cat /opt/mackerel-agent/plugins/meta/mackerelio/mackerel-plugin-sample/release_tag
v0.0.3
``` …
=> Add --upgrade option to plugin install.

.travis.yml, appveyor.yml
- Linux: 1.9 (Currently build failing) => 1.10
- Windows: latest(implicitly 1.10) => explicit 1.10
=> Build with Go 1.10

commands.go, throw.go, throw_test.go
- Retry with exponential backoff (min interval is 15 sec and Max is 5 min).
- Don't retry when HTTP response is 4xx
demo:
```
[github.com/mackerelio/mkr]$ echo "tcp.CLOSING 0 1397031808" | ./mkr --apibase http://localhost:5000/ --conf /usr/local/etc/mackerel-agent.conf throw --host shiba
error API request failed: 404 Not Found
[github.com/mackerelio/mkr]$ echo "tcp.CLOSING 0 1397031808" | ./mkr --apibase http://localhost:5000/ --conf /usr/local/etc/mackerel-agent.conf throw --host shiba
error API request failed: 500 Internal Server Error
[github.com/mackerelio/mkr]$ echo "tcp.CLOSING 0 1397031808" | ./mkr --apibase http://localhost:5000/ --conf /usr/local/etc/mackerel-agent.conf throw --host shiba --max-retry 2
warning Failed to request. will retry after 15 seconds. Error: API request …
```
=> add Retry feature and --max-retry option to `mkr throw`

Dockerfile, Makefile
Alternative of #164. This reduces the docker image size to 14.3MB (before: 19.9MB).
=> Omit symbol table and debug information from the executable

logger/logger.go
The progress logs should be output to Stderr.
Although it is an incompatible change, it seems not to be a big problem.
=> logs to Stderr

alerts.go, alerts_test.go
example:
```
aaa 2018-10-26 17:05:52 CRITICAL HTTP CRITICAL: Get https://127.0.0.1/: dial tcp 127.0.0.1:443: connect: connection refused xxxproxy22.local standby [XXX:proxy]
bbb 2018-10-25 16:35:04 CRITICAL connectivity yyybackend10.local working [YYY:backend]
```
Handling:
- display up to 100 runes
- trim at first newline (`[\r\n]`)
=> show alert.Message as monitor message in mkr alerts list

commands.go
Updating the display name by `mkr update --displayName foobar` removes the interfaces information unexpectedly. This pull request fixes the params to keep the interfaces information. Other fields are not necessarily filled because they are not deleted when empty.
=> update subcommand should keep the interface infromation

alerts.go
This pull request fixes the problem the command mkr alerts truncates to 100 alerts in default.
=> Fix the default limit of mkr alerts

commands.go, logger/logger.go, mkr.go, wrap/command.go, wrap/result.go, wrap/testdata/dummy.conf, wrap/testdata/stub.go, wrap/wrap.go, wrap/wrap_test.go
Wrap a batch command with specifying it as arguments. If the command failed
with non-zero exit code, it sends a report to Mackerel and raises an alert.
It is useful for cron jobs etc.
```
% mkr wrap -- /path/to/your-batch
```
- command.go
- entry point of the `wrap` subcommand
- wrap.go
- main logic is here
- result.go
- define `type result` to represent the command result
=> add wrap subcommand to monitor batch jobs to run with cron etc

alerts.go, annotations.go, commands.go, format/format.go, hosts/app.go, monitors.go, org.go
This is the first step to improve test coverage.
Future plans:
- Split each command to packages (like hostApp)
- Each app has client interface so that we can mock in tests
- Each app has outStream io.Writer so that we can test
- Write much more and more tests!
I think we can start with hosts  subcommand or org subcommand (which is very easy!).
=> Add out stream argument to format.PrettyPrintJSON

hosts/app.go, hosts/command.go, mackerelclient/client.go, mackerelclient/mock_client.go, mackerelclient/new.go
In order to write mock tests, I want to introduce interface for Mackerel API Client. This is much like https://github.com/mackerelio/mackerel-container-agent/blob/2d193452f862b96a61364e95e4dbf450bb6ac17e/api/client.go.
Future plans:
- Split subcommands to packages (like hostsApp)
- Add methods to the Client interface if required by the commands.
- Add mock tests.
- Remove mackerelclient.NewFromContext.
I want to change import alias mkr to mackerel, so that we can change the top directory of this repository to mkr package (move main.go to cmd/mkr/).
=> Introduce Client interface for Mackerel API

commands.go, dashboards.go
I found some links in the command help are the links to Japanese version.
=> [nit] Fix link in command helps to english versions

commands.go, mackerelclient/client.go, mackerelclient/mock_client.go, services/app.go, services/app_test.go, services/command.go
- Separate services subcommand implementation to ./services/
- Add tests
=> Create services package and add tests for services subcommand

wrap/result.go, wrap/testdata/long.go, wrap/wrap_test.go
It would be useful to show both heading and leading messages of the output. The length is limited to the spec of api https://mackerel.io/api-docs/entry/check-monitoring#post.
Resolves #199.
=> [wrap] Improve message truncation algorithm

Dockerfile, appveyor.yml
*golang:alpine3.7* image's Go version is 1.10.
This version don't support Go Modules.
related pull requests:
* #205
* #207
=> upgrade builder image and enable go modules

Makefile
The import path `<repository>/<branch>` is accepted only module-aware mode.
Currently `github.com/mholt/archiver/v3` uses above notation, so go-build can't find archiver/v3 package on GOPATH mode.
=> always set GO111MODULE=on

alerts.go, alerts_test.go, annotations.go, commands.go, dashboards.go, hosts/app.go, hosts/app_test.go, mackerelclient/client.go, mackerelclient/mock_client.go, mackerelclient/new.go, monitors.go, monitors_test.go, org/app_test.go, services/app_test.go, throw.go, throw_test.go, wrap/wrap.go, wrap/wrap_test.go
closes: https://github.com/mackerelio/mkr/issues/261
- Stop using the `mkr` alias and use the package name `mackerel` instead
- Stop using the `mackerel` alias since it has no meaning
I think I've covered all the imports:
```sh
$ git grep "mackerel-client-go" -- "*.go"
alerts.go:      "github.com/mackerelio/mackerel-client-go"
alerts_test.go: "github.com/mackerelio/mackerel-client-go"
annotations.go: "github.com/mackerelio/mackerel-client-go"
commands.go:    "github.com/mackerelio/mackerel-client-go"
dashboards.go:  "github.com/mackerelio/mackerel-client-go"
hosts/app.go:   "github.com/mackerelio/mackerel-client-go"
hosts/app_test.go:      "github.com/mackerelio/mackerel-client-go"
mackerelclient/client.go:import "github.com/mackerelio/mackerel-client-go" …
```
=> Stop using alias imports for mackerel-client-go for simplicity

annotations.go
fix #272 
I searched CLI usage code with `git grep '\[-' **/*.go` and manually checked flags validation code.
----
One more thing: It will be found that no validation in Go but done by server-side and not found above `git-grep`.
=> show mandantory flags usage in modern CLI manner

Makefile
32bit Darwin is an ancient one, so remove from crossbuild targets.
ref: https://github.com/mackerelio/mackerel-agent/pull/600
(note: Go 1.14 is the last Go release to support 32-bit binaries on macOS: https://golang.org/doc/go1.14)
=> Stop building 32bit Darwin artifacts

monitors.go
At doMonitorsPull(), the default file name "monitors.json" are defined twice. However, it is supposed to be enough at once.
doMonitorsPull() のなかで、 monitors.json を `monitorSaveRules()` でのファイル保存時と、 ログ出力時で、別々にoptを解決していますが、一箇所で十分になるのではと思い、動作には変わりはありませんが、PR出させていただきました。
Operation Check Result
```
-> % ./mkr monitors pull
info Monitor rules are saved to 'monitors.json' (14 rules).
kazukihigashiguchi@BASE-P0126-MBP [19時09分06秒] [~/go/src/github.com/hgsgtk/mkr] [refactor/filepath *]
-> % ./mkr monitors pull --file-path=hoge.json
info Monitor rules are saved to 'hoge.json' (14 rules).
```
=> define default file name while doMonitorsPull() at once

packaging/deb/debian/control
I've introduced `Architecture: any` at #310 but its side-effects was changing package filename unexpectedly.
So I revert that changes.
=> revert changing filename

.travis.yml, Makefile
Add armhf(32bit ARM with hardfloat) Debian/Raspberry Pi OS package support.
The package has already been tested on my own Raspberry Pi Zero, and it works fine.
=> Add armhf Debian package to GitHub release

hosts/app.go, hosts/app_test.go
related: https://github.com/mackerelio/mkr/issues/324
initialize hostsFormat with make to avoid print "null" when no hosts found.
=> Print empty array if hosts not found

monitors.go
This bug introduced #348 , and released it since 2021-02-16 05:53 UTC.
effects: `mkr monitors {diff|push}`
=> fix condition to delete monitors

go.mod, go.sum
dependabot cannot create a pull request to update modules now, because `go mod` command causes error ( https://github.com/mackerelio/mkr/network/updates/113751564 ).
I arranged go.sum and executed `go mod tidy` manually to fix this problem.
=> [nit] Fix go mod error so that go modules can be updated

format/format.go, mackerelclient/client.go, mackerelclient/mock_client.go, status/app.go
This patch adds to mkr the ability to output a list of host-metrics that the host has.
The output of the metric list will only work with `mkr status -v` (verbose mode), so there will be no performance impact in general use.
```
$ mkr status 4Hkc5RWzUQG
{
"id": "4Hkc5RWzUQG",
...
"ipAddresses": {
...
}
}
$ mkr status -v 4Hkc5RWzUQG
{
"id": "4Hkc5RWzUQG",
...
"interfaces": [
...
],
"metrics": [
"cpu.guest.percentage",
...
"memory.used"
]
}
```
=> improve `mkr status -v` to show host metrics

.github/workflows/ci.yml, Makefile, packaging/deb-v2/debian/rules, packaging/deb/debian/rules
Changed to use xz format for compressing debian packages. refer https://github.com/mackerelio/mackerel-agent-plugins/pull/981
The environment ubuntu-latest for GitHub Actions is ubuntu 22.04.
It turns out that glibc is new and the built binary compatibility is broken in some environments.
So I made a change to build with CGO_ENABLED=0
=> added compile option, fix packaging format

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/create-release-pr.yml
This repository's workflows look antiquated. Deprecated features and runtimes of Github Actions will soon be unavailable.
So we activate dependabot for GitHub Actions to automate updates.
=> Enables Dependabot version updates for GitHub Actions

commands.go, metric_names/command.go
Hi. I added metric-names subcommand.
metric-names fetches metric names of the host or service.
```
mkr metric-names --help
NAME:
mkr metric-names - Fetch metric names
USAGE:
mkr metric-names [command options] [--host | -H <hostId>] [--service | -s <service>] [--jq <formula>]
DESCRIPTION:
Fetch metric names of 'host metric' or 'service metric'.
Requests "/api/v0/hosts/<hostId>/metric-names" or "/api/v0/services/<serviceName>/metric-names".
See https://mackerel.io/ja/api-docs/entry/hosts#metric-names, https://mackerel.io/ja/api-docs/entry/services#metric-names
OPTIONS:
--host value, -H value     Fetch host metric names of <hostID>.
--service value, -s value  Fetch service metric names of <service>.
--jq value                 Filter response values using jq syntax
```
=> Add metric-names subcommand.

annotations/command.go
Added `--description-file` option to `annotations create` and `annotations update` commands. You can also read from stdin by passing "-" in place of the file path.
```sh
echo "Hello." | ./mkr -conf /opt/homebrew/etc/mackerel-agent.conf annotations create --service test --title test --from $(date '+%s') --to $(date '+%s') --description-file -
```
```json
{
"id": "4UsqfziHEew",
"title": "test",
"description": "Hello.\n",
"from": 1689863144,
"to": 1689863144,
"service": "test"
}
```
```sh
echo "Hello2." | ./mkr -conf /opt/homebrew/etc/mackerel-agent.conf annotations update --id 4UsqfziHEew --service test --title test --from $(date '+%s') --to $(date '+%s') --description-file -
```
```json
{
"id": "4UsqfziHEew",
"title": "test",
"description": "Hello2.\n",
"from": 1689863321,
"to": …
```
=> read annotation's description from file or stdin

.github/dependabot.yml, .github/workflows/ci.yml, Dockerfile, go.mod
- use Go 1.21 to build binaries and container image
- set minimal supported version to 1.20 (because checkers uses strings.CutPrefix)
- refactor workflows and dependabot config
=> update Go version to 1.21 and 1.20 by using reusable workflow

dashboards/command.go, go.mod, monitors/command.go, monitors/command_test.go
Passing a JSON file with a UTF-8 BOM to `mkr dashboards push --file-path` causes an error that is difficult for users to understand.
```
error invalid character 'ï' looking for beginning of value
```
I understand that "JSON files must not contain a BOM", but I thought it would be more user-friendly to ignore the BOM part and read the file without making an error, so I made a patch.
Test
```
$ mkr dashboards push --file-path t-nobom.json
$ mkr dashboards push --file-path t-withbom.json
error invalid character 'ï' looking for beginning of value
$ ./mkr dashboards push --file-path t-nobom.json
$ ./mkr dashboards push --file-path t-withbom.json
```
[t-nobom.json](https://github.com/mackerelio/mkr/files/13956859/t-nobom.json)
[t-withbom.json](https://github.com/mackerelio/mkr/files/13956861/t-w …
=> accept UTF8-BOM when reading dashboard or monitor from JSON file

Makefile
Hi!
The latest release binaries seems to be build dynamic linked.
For example https://github.com/mackerelio/mkr/releases/download/v0.55.0/mkr_linux_amd64.tar.gz
```console
$ curl -sLO https://github.com/mackerelio/mkr/releases/download/v0.55.0/mkr_linux_amd64.tar.gz
$ tar xvf mkr_linux_amd64.tar.gz
$ ldd mkr_linux_amd64/mkr
linux-vdso.so.1 (0x00007ffe0359c000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6c654a7000)
/lib64/ld-linux-x86-64.so.2 (0x00007f6c656de000)
```
But, the mkr binary in Debian packages are statically linked.
```console
$ ldd /usr/bin/mkr
not a dynamic executable
```
I hope to use the release binaries in non-glibc environments (like Alpine Linux).
Currently, CGO_ENABLED=0 is set only when building via 'make build'. But the setting does not affect 'make cross', …
=> Always set CGO_ENABLED=0

org/app.go, org/app_test.go, org/command.go
It would be helpful if `mkr org` subcommand has `--jq` option like other subcommands.
For example:
```
$ mkr org --jq '.name'
myorg
$ mkr org --jq '.displayName'
My Organization
```
Here is a patch to add `--jq` option to `org` subcommand and test code.
I referred the code of `channels` subcommand.
=> Add `--jq` option to `org` sub command

monitors/command.go
validateRules have returned without checking all monitor rules.
=> fix unintentionally return in validateRules

monitors/command.go, monitors/command_test.go
I make mkr support "query monitoring", which is a new monitoring rule on Mackerel.
First I have got monitors.json using `mkr monitors pull` and edited it to add a new query rule `new query`.
Then, I tested two command `diff` and `push` as following.
``` console
% ./mkr monitors diff
Summary: 0 modify, 1 append, 0 remove
+{
+  "name": "new query",
+  "type": "query",
+  "query": "http.client.duration.p90{service.name=\"web-app\"}",
+  "operator": "<",
+  "warning": 1,
+  "critical": null,
+  "legend": "{{http.status_code}}"
+},
% ./mkr monitors push
info Create a new rule.
{
"name": "new query",
"type": "query",
"query": "http.client.duration.p90{service.name=\"web-app\"}",
"operator": "<",
"warning": 1,
"critical": null,
"legend": "{{http.status_code}}"
},
```
After that, I checked the …
=> Support query monitorings

alerts/command.go
Fixed an incorrect description of the `--host-status` (`-S`) option
=> host-status option doesn't receive File in alerts command

.github/workflows/ci.yml
Same as https://github.com/mackerelio/mackerel-agent-plugins/pull/1247 .
The CI for the master branch is failing due to the absence of the build-essential:native package, as seen in [this run](https://github.com/mackerelio/mkr/actions/runs/12924557525/job/36043964051). It appears that the cause is the change to Ubuntu 24.04, as the runner is specified to use ubuntu-latest in GHA.
This pull request specifies the runner to use ubuntu-22.04.
=> Fix CI build

go.mod, go.sum
mackerel-client-go v0.35.0 and v0.36.0 support new fields in some APIs updated recently.
=> update mackerel-client-go to v0.36.0

alerts/command.go, go.sum
Implemented getting alert logs command
- https://pkg.go.dev/github.com/mackerelio/mackerel-client-go#Client.FindAlertLogs
```
NAME:
mkr alerts logs - get alert logs
USAGE:
mkr alerts logs [command options] <alertId> [--limit | -l] [--jq <formula>]
DESCRIPTION:
Get alert logs.
OPTIONS:
--limit value, -l value  Set the number of alert logs to display (default: 100)
--jq value               Filter response values using jq syntax
```
=> Implement find alert logs command

plugin/install_target.go, plugin/install_target_test.go
Since we sometimes hit the GitHub API rate limit when running mkr plugin install across many servers using our provisioning tool, we added code to pull the latest version straight from the github.com URL.
=> Get plugin's releaseTag from the releases URL instead of using api
